alter table public.games add column if not exists max_players integer not null default 10 check (max_players between 1 and 30);

-- The client-side check is for UX; this trigger is the authoritative guard
-- against two organizers accepting the final slot at the same time.
create or replace function public.enforce_game_capacity()
returns trigger language plpgsql security definer set search_path = public as $$
declare capacity integer; accepted_count integer;
begin
  if new.status = 'accepted' and (tg_op = 'INSERT' or old.status is distinct from 'accepted') then
    select max_players into capacity from public.games where id = new.game_id for update;
    select count(*) into accepted_count from public.game_requests
      where game_id = new.game_id and status = 'accepted' and id <> coalesce(new.id, -1);
    if accepted_count >= capacity then
      raise exception 'MATCH_CAPACITY_REACHED';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists enforce_game_capacity_before_accept on public.game_requests;
create trigger enforce_game_capacity_before_accept
before insert or update of status on public.game_requests
for each row execute function public.enforce_game_capacity();

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  title text not null,
  body text not null,
  type text not null,
  game_id bigint references public.games(id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_id_idx on public.notifications (user_id, created_at desc);
alter table public.notifications enable row level security;
drop policy if exists "notifications_select" on public.notifications;
drop policy if exists "notifications_update" on public.notifications;
drop policy if exists "notifications_insert" on public.notifications;
create policy "notifications_select" on public.notifications for select using (auth.uid() = user_id);
create policy "notifications_update" on public.notifications for update using (auth.uid() = user_id);
create policy "notifications_insert" on public.notifications for insert with check (
  auth.uid() = user_id or exists (
    select 1 from public.games where games.id = notifications.game_id and games.user_id = auth.uid()
  )
);

create or replace function public.notify_match_request()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.notifications (user_id, title, body, type, game_id)
  select g.user_id, 'طلب انضمام جديد', 'لديك لاعب جديد بانتظار الموافقة.', 'join_request', new.game_id
  from public.games g where g.id = new.game_id;
  return new;
end;
$$;
drop trigger if exists game_request_notification on public.game_requests;
create trigger game_request_notification after insert on public.game_requests
for each row execute function public.notify_match_request();

create or replace function public.notify_request_status()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if old.status is distinct from new.status then
    insert into public.notifications (user_id, title, body, type, game_id)
    values (new.user_id,
      case when new.status = 'accepted' then 'تم قبول طلبك' else 'تم رفض طلبك' end,
      case when new.status = 'accepted' then 'أنت الآن ضمن قائمة لاعبي المباراة.' else 'يمكنك استكشاف مباريات أخرى متاحة.' end,
      'request_' || new.status::text, new.game_id);
  end if;
  return new;
end;
$$;
drop trigger if exists game_request_status_notification on public.game_requests;
create trigger game_request_status_notification after update of status on public.game_requests
for each row execute function public.notify_request_status();

create or replace function public.notify_game_cancelled()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if old.status is distinct from new.status and new.status = 'cancelled' then
    insert into public.notifications (user_id, title, body, type, game_id)
    select r.user_id, 'تم إلغاء المباراة', 'ألغى المنظم المباراة التي انضممت إليها.', 'game_cancelled', new.id
    from public.game_requests r where r.game_id = new.id and r.status = 'accepted';
  end if;
  return new;
end;
$$;
drop trigger if exists game_cancelled_notification on public.games;
create trigger game_cancelled_notification after update of status on public.games
for each row execute function public.notify_game_cancelled();
